### ISSUE TITLE
New styling for API Javadoc is very counter-productive; please provide normal API build

### ISSUE THREAD

**Issue by archiecobbs** [vaadin/vaadin.com#61]
A few days ago the HTML styling of `https://vaadin.com/api/` changed to make it look like the rest of the site. To be frank, I hate this change.

Although this makes it look "prettier", the practical effect for developers, who are the primary consumers of this page, is to make it more difficult to find information. At least, that's the case for me.

API Javadoc is reference material, and it should be optimized for that goal, not for appearance. When you make the styling completely inconsistent with all of the rest of the world's API Javadoc, you create a new, unique, non-reusable visual language/dialect that Vaadin developers have to learn anew. All of the visual intuition that we as developers have and apply to the rest of the world's open source software is now half-useless.

I don't expect you to un-do all of this new work. However I'd respectfully ask that you please provide an alternative URL containing the normally-styled API Javadoc... or at least styled in the way it used to be a couple of weeks ago.

**Comment by vaadin-pagespeed** [comment]
Hi @archiecobbs,

I'm sad to hear that! Actually, the alignment with the rest of the website is just a site-effect of the new implementation which is much more flexible in resolving and displaying Javadocs in general.

We already got quite a lot user feedback and extended our Javadocs browser accordingly and we are happy to improve it even further. But for that I have to understand your needs first.

- Does it break your workflow at the moment? So, is there some functionality missing old Javadocs provided?
- Is it about the styling of the class details? Maybe the attributes, methods etc. are not clear enough?
- Or is it about the styling in general because it does not look like default Javadocs in a way we (as developers) are used to it?

Cheers,
  Paul

**Comment by paulroemer** [comment]
Hi @archiecobbs,

I'm sad to hear that! Actually, the alignment with the rest of the website is just a site-effect of the new implementation which is much more flexible in resolving and displaying Javadocs in general.

We already got quite a lot user feedback and extended our Javadocs browser accordingly and we are happy to improve it even further. But for that I have to understand your needs first.

- Does it break your workflow at the moment? So, is there some functionality missing old Javadocs provided?
- Is it about the styling of the class details? Maybe the attributes, methods etc. are not clear enough?
- Or is it about the styling in general because it does not look like default Javadocs in a way we (as developers) are used to it?

Cheers,
  Paul

**Comment by archiecobbs** [comment]
Thanks. I'd say "it does not look like default Javadocs in a way we (as developers) are used to it" is the right description. It doesn't look objectively bad, just different.

There are indeed some functional differences that make things worse. For example, now the package list and class list are in a single pane (they used to be two panes). This makes navigation of the Vaadin class tree (which is fairly large) even more cumbersome because it "flattens" the tree. Also, there is a lot more whitespace in general which means more scrolling.

But again, the main problem for me at least is that my eye is trained to look for certain colors and visual patterns, and now that training has been invalidated.

**Comment by vaadin-pagespeed** [comment]
> I'd say "it does not look like default Javadocs in a way we (as developers) are used to it" is the right description. It doesn't look objectively bad, just different.

Ok, got it. We will discuss it tomorrow.

> For example, now the package list and class list are in a single pane (they used to be two panes). This makes navigation of the Vaadin class tree (which is fairly large) even more cumbersome because it "flattens" the tree.

That's interesting. I am more used to use the browser search to find what I need. Obviously, in this case I already have to know for what I am looking for. I normally do not navigate Javadocs that much.
Besides adding kind of "good old style" mode, how do you think we can simplify the navigation. It sounds like even with old Javadocs it is a pain in the ass but you got used to it. Can you explain some more details about the workflow? Or do you have ideas already? That's the good thing about the new implementation. We are able to implement new features to help developers quite easily.

> Also, there is a lot more whitespace in general which means more scrolling.

True, and we have some fixes for that in the pipe already.

**Comment by archiecobbs** [comment]
> It sounds like even with old Javadocs it is a pain in the ass but you got used to it. Can you explain some more details about the workflow? Or do you have ideas already? 

I just scroll as needed. It's already somewhat cumbersome with the old styling, but I'm used to it...

**Comment by paulroemer** [comment]
What are your thoughts nowadays?

**Comment by archiecobbs** [comment]
Much better, thanks.

Is there a reason to put a line break between open and closing parentheses? Might just be a glitch:

<img width="640" alt="screen shot 2018-08-20 at 10 41 03 am" src="https://user-images.githubusercontent.com/545866/44350742-b4657400-a465-11e8-8a1a-7a50fd821bab.png">

**Comment by mickoyuh** [comment]
This is fixed now. 

![image](https://user-images.githubusercontent.com/26737661/45206069-bebca600-b28c-11e8-954f-704ef4acc1aa.png)

**Comment by mickoyuh** [comment]
Thank you for very good feedback Archie!

**Comment by archiecobbs** [comment]
This issue was closed, yet you did not provide a normal API Javadoc build - could you please provide one (or at least render judgement on the idea)?

**Comment by archiecobbs** [comment]
I was wrong, Javadoc "classic" does exist and is here (for example):
* https://vaadin.com/download/release/8.6/8.6.2/docs/api/
* https://vaadin.com/download/release/7.7/7.7.16/docs/api/
